fixtures:
  repositories:
    archive: "https://github.com/voxpupuli/puppet-archive.git"
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    puppet_agent: 
      repo: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
      ref: v4.19.0
    provision: 'https://github.com/puppetlabs/provision.git'
  symlinks:
    java: "#{source_dir}"
